version: "2"

linters:
  default: none

  enable:
    - asasalint
    - asciicheck
    - bidichk
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - forcetypeassert
    - funcorder
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - godoclint
    - godox
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - iotamixing
    - loggercheck
    - makezero
    - mirror
    # - mnd # giving too many false positives
    - modernize
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - paralleltest
    - perfsprint
    - predeclared
    - reassign
    - recvcheck
    - revive
    - sloglint
    - staticcheck
    - tagliatelle
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - wrapcheck

  settings:
    copyloopvar:
      check-alias: true

    revive:
      rules:
        - name: package-comments
          disabled: true

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
    - gci
  
  settings:
    gofumpt:
      extra-rules: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
  uniq-by-line: true
  whole-files: false
