// Code generated by "stringer -type=tokenType"; DO NOT EDIT.

package read

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[illegal-0]
	_ = x[rParen-1]
	_ = x[lParen-2]
	_ = x[quote-3]
	_ = x[number-4]
	_ = x[symbol-5]
	_ = x[eof-6]
}

const _tokenType_name = "illegalrParenlParenquotenumbersymboleof"

var _tokenType_index = [...]uint8{0, 7, 13, 19, 24, 30, 36, 39}

func (i tokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_tokenType_index)-1 {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[idx]:_tokenType_index[idx+1]]
}
